# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ms-sql-server:
    image: kiter0211/qlbvxk-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "myPass123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
